/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/achievements': RouteRecordInfo<
      '/achievements',
      '/achievements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/equipment': RouteRecordInfo<
      '/equipment',
      '/equipment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/life': RouteRecordInfo<
      '/life',
      '/life',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/progress': RouteRecordInfo<
      '/progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/research': RouteRecordInfo<
      '/research',
      '/research',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/team': RouteRecordInfo<
      '/team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | '/team/[id]'
      | '/team/undergraduate-[id]'
    >,
    '/team/[id]': RouteRecordInfo<
      '/team/[id]',
      '/team/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/team/undergraduate-[id]': RouteRecordInfo<
      '/team/undergraduate-[id]',
      '/team/undergraduate-:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/achievements.vue': {
      routes:
        | '/achievements'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/pages/equipment.vue': {
      routes:
        | '/equipment'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/life.vue': {
      routes:
        | '/life'
      views:
        | never
    }
    'src/pages/progress.vue': {
      routes:
        | '/progress'
      views:
        | never
    }
    'src/pages/research.vue': {
      routes:
        | '/research'
      views:
        | never
    }
    'src/pages/team.vue': {
      routes:
        | '/team'
        | '/team/[id]'
        | '/team/undergraduate-[id]'
      views:
        | 'default'
    }
    'src/pages/team/[id].vue': {
      routes:
        | '/team/[id]'
      views:
        | never
    }
    'src/pages/team/undergraduate-[id].vue': {
      routes:
        | '/team/undergraduate-[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
